import { Plant } from "./classes/plants";

export const sample_plants: Plant[] = [
    {
        id: 0,
        name: "Lucky bamboo",
        scientificName: "Dracaena sanderiana",
        price: 9.99,
        description: "A small, easy-to-care-for houseplant with upright stems and bright green leaves. It thrives in water or well-draining soil and prefers medium to low light. Also known as ribbon plant or friendship bamboo.",
        inStock: true,
        category: ["houseplant"],
        water: 110,
        toxicity: true,
        humidity: "High humidity",
        temperature: "20-28",
        sunlight: "Partial sun",
        toughness: "High",
        tips: ["Is known for being undemanding", "Overwatering should be avoided to prevent root rot", "Can adjust to low light conditions"],
        promotion: false,
        rating: 4.7,
        bestseller: false,
        indoor: true,
        outdoor: false,
        maintenance: "Weekly",
        expierience: "Beginner",
        space: "Medium Space (e.g. Windowsill)",
        purpose: "Decoration",
        petfriendly: false,
        allergyfriendly: true,
        imageUrl: ["/ Dracaena_sanderiana1.png", "/ Dracaena_sanderiana2.png", "/ Dracaena_sanderiana3.png"],
        nickname: "",
        size: NaN,
        age: NaN,
        pinned: false,
        timeBetweenSessions: 10080,
        waterTime: new Date(Date.now() + 60 * 1000)
    },
    {
        id: 1,
        name: "Weeping fig",
        scientificName: "Ficus benjamina",
        price: 11.99,
        description: "To be added",
        inStock: true,
        category: ["houseplant", "tree"],
        water: 20,
        toxicity: true,
        humidity: "High humidity",
        temperature: "20-35",
        sunlight: "Partial to full sun",
        toughness: "High",
        tips: ["People with allergies should avoid this plant", "One of the most popular houseplants"],
        promotion: false,
        rating: 4.4,
        bestseller: true,
        indoor: true,
        outdoor: false,
        maintenance: "Weekly",
        expierience: "Intermediate",
        space: "Large Space (e.g. large Room)",
        purpose: "Decoration",
        petfriendly: false,
        allergyfriendly: false,
        imageUrl: ["/Ficus_benjamina1.png", "/Ficus_benjamina1.png", "/Ficus_benjamina1.png"],
        nickname: "",
        size: 0,
        age: 0,
        pinned: true,
        timeBetweenSessions: 1440,
        waterTime: new Date(Date.now() + 60 * 1000)
    },
    {
        id: 2,
        name: "Sweet basil",
        scientificName: "Ocimum basilicum",
        price: 5.99,
        description: "A tender, aromatic herb native to tropical regions. It features bright green, oval-shaped leaves with a distinct, slightly peppery fragrance. Sweet basil thrives in warm temperatures, partial sun, and moist but well-draining soil. Widely used in culinary applications, fresh basil leaves add a wonderful flavor to tomato dishes, pesto, salads, and many other recipes. Beyond its culinary uses, basil is also considered easy to grow indoors, making it a popular choice for home gardeners and kitchens.",
        inStock: true,
        category: ["Herb", "houseplant"],
        water: 15,
        toxicity: false,
        humidity: "Medium humidity",
        temperature: "20-38",
        sunlight: "Partial sun",
        toughness: "Medium",
        tips: ["The leaves can be eaten (fresh or dried)", "O"],
        promotion: false,
        rating: 4.6,
        bestseller: false,
        indoor: true,
        outdoor: true,
        maintenance: "Weekly",
        expierience: "Beginner",
        space: "Medium Space (e.g. Windowsill)",
        purpose: "Food (e.g. herbs or vegetables",
        petfriendly: true,
        allergyfriendly: true,
        imageUrl: ["/Ocimum_basilicum1.png", "/Ocimum_basilicum2.png", "/Ocimum_basilicum3.png"],
        nickname: "",
        size: 0,
        age: 0,
        pinned: false,
        timeBetweenSessions: 10080,
        waterTime: new Date(Date.now() + 60 * 1000)
    },
    {
        id: 3,
        name: "Jade plant",
        scientificName: "Crassula ovata",
        price: 9.99,
        description: "A popular succulent plant prized for its attractive, glossy leaves and ease of care. The thick, oval-shaped leaves store water, giving the plant a plump and resilient appearance. Jade plants come in various shapes and sizes, depending on pruning and cultivation. They prefer bright, indirect sunlight and well-draining soil, making them suitable for sunny windowsills. Water them moderately, allowing the soil to dry out completely between waterings. Jade plants are generally low-maintenance and can tolerate some neglect, making them ideal for beginner plant owners. They are believed to bring good luck and fortune, contributing to their nicknames Lucky plant and Money tree.",
        inStock: true,
        category: ["succulent", "houseplant"],
        water: 50,
        toxicity: true,
        humidity: "",
        temperature: "15-25",
        sunlight: "Partial sun",
        toughness: "High",
        tips: ["Crassula ovata can purify air and absorb harmful gases."],
        promotion: false,
        rating: 4.1,
        bestseller: false,
        indoor: true,
        outdoor: false,
        maintenance: "Weekly",
        expierience: "Beginner",
        space: "Medium Space (e.g. Windowsill)",
        purpose: "Decoration",
        petfriendly: false,
        allergyfriendly: true,
        imageUrl: ["/Crassula_ovata1.png", "/Crassula_ovata2.png", "/Crassula_ovata3.png"],
        nickname: "",
        size: 0,
        age: 0,
        pinned: false,
        timeBetweenSessions: 10080,
        waterTime: new Date(Date.now() + 60 * 1000)
    },
    {
        id: 4,
        name: "Mexican snow ball",
        scientificName: "Echeveria elegans",
        price: 7.99,
        description: "A beautiful succulent with pale green-blue, rosette-shaped leaves. Known for its low-maintenance needs, it thrives in bright sunlight and infrequent watering.",
        inStock: true,
        category: ["succulent"],
        water: 10,
        toxicity: false,
        humidity: "low humidity",
        temperature: "20-38",
        sunlight: "Direkt Sunlight",
        toughness: "High",
        tips: ["Can survive a complete desiccation"],
        promotion: true,
        rating: 4.7,
        bestseller: false,
        indoor: true,
        outdoor: true,
        maintenance: "Minimal",
        expierience: "Beginner",
        space: "Small space (e.g. small desk)",
        purpose: "Decoration",
        petfriendly: true,
        allergyfriendly: true,
        imageUrl: ["/Echeveria_elegans1.png", "/Echeveria_elegans2.png", "/Echeveria_elegans3.png"],
        nickname: "",
        size: NaN,
        age: NaN,
        pinned: false,
        timeBetweenSessions: 1440,
        waterTime: new Date(Date.now() + 60 * 1000)
    },
    {
        id: 5,
        name: "green sansevieria",
        scientificName: "Sansevieria trifasciata Laurentii",
        price: 19.99,
        description: "Easy care succulent with upright sword-shaped leaves. Air purifying and tolerates low light.",
        inStock: true,
        category: ["succulent"],
        water: 20,
        toxicity: true,
        humidity: "high humidity",
        temperature: "26-35",
        sunlight: "Partial to full sun",
        toughness: "Medium",
        tips: [],
        promotion: false,
        rating: 3.9,
        bestseller: true,
        indoor: true,
        outdoor: true,
        maintenance: "Monthly",
        expierience: "Beginner",
        space: "Medium Space (e.g. Windowsill)",
        purpose: "Air purification",
        petfriendly: false,
        allergyfriendly: true,
        imageUrl: ["/Sansevieria_trifasciata_Laurentii1.png", "/Sansevieria_trifasciata_Laurentii2.png", "/Sansevieria_trifasciata_Laurentii3.png"],
        nickname: "",
        size: NaN,
        age: NaN,
        pinned: false,
        timeBetweenSessions: 43200,
        waterTime: new Date(Date.now() + 60 * 1000)
    },
    {
        id: 6,
        name: "English ivy",
        scientificName: "Hedera helix",
        price: 3.99,
        description: " A climbing vine with lobed, dark green leaves. It is known for its ability to grow in various conditions and its use as a ground cover or ornamental plant.",
        inStock: true,
        category: ["houseplant"],
        water: 30,
        toxicity: true,
        humidity: "High humidity",
        temperature: "25-30",
        sunlight: "Full sun",
        toughness: "Medium",
        tips: [],
        promotion: false,
        rating: 3.5,
        bestseller: false,
        indoor: true,
        outdoor: true,
        maintenance: "Monthly",
        expierience: "Beginner",
        space: "Medium Space (e.g. Windowsill)",
        purpose: "Decoration",
        petfriendly: false,
        allergyfriendly: false,
        imageUrl: ["/Hedera_helix1.png", "/Hedera_helix2.png", "/Hedera_helix3.png"],
        nickname: "",
        size: NaN,
        age: NaN,
        pinned: false,
        timeBetweenSessions: 43200,
        waterTime: new Date(Date.now() + 60 * 1000)
    },
    {
        id: 7,
        name: "Common daisy",
        scientificName: "Bellis perennis",
        price: 2.99,
        description: "To be added",
        inStock: true,
        category: ["wild flower"],
        water: 15,
        toxicity: false,
        humidity: "medium humidity",
        temperature: "20-40",
        sunlight: "Full sun",
        toughness: "Medium",
        tips: [],
        promotion: false,
        rating: 3.5,
        bestseller: false,
        indoor: true,
        outdoor: true,
        maintenance: "Weekly",
        expierience: "Beginner",
        space: "Small space (e.g. small desk)",
        purpose: "Decoration",
        petfriendly: true,
        allergyfriendly: true,
        imageUrl: ["/Bellis_perennis1.png", "/Bellis_perennis2.png", "/Bellis_perennis3.png"],
        nickname: "",
        size: NaN,
        age: NaN,
        pinned: false,
        timeBetweenSessions: 10080,
        waterTime: new Date(Date.now() + 60 * 1000)
    },
    {
        id: 8,
        name: "Tomato plant",
        scientificName: "Solanum lycopersicum",
        price: 12.99,
        description: "To be added",
        inStock: true,
        category: ["food plant"],
        water: 40,
        toxicity: false,
        humidity: "high humidity",
        temperature: "20-35",
        sunlight: "Full sun",
        toughness: "Medium",
        tips: [],
        promotion: false,
        rating: 4.8,
        bestseller: false,
        indoor: false,
        outdoor: true,
        maintenance: "Weekly",
        expierience: "Intermediate",
        space: "Medium Space (e.g. Windowsill)",
        purpose: "Food (e.g. herbs or vegetables",
        petfriendly: true,
        allergyfriendly: true,
        imageUrl: ["/Solanum_lycopersicum1.png", "/Solanum_lycopersicum2.png", "/Solanum_lycopersicum3.png"],
        nickname: "",
        size: NaN,
        age: NaN,
        pinned: false,
        timeBetweenSessions: 720,
        waterTime: new Date(Date.now() + 60 * 1000)
    },
    {
        id: 9,
        name: "Lemon tree",
        scientificName: "Citrus limon",
        price: 35.99,
        description: "To be added",
        inStock: true,
        category: ["tree"],
        water: 30,
        toxicity: false,
        humidity: "high humidity",
        temperature: "25-35",
        sunlight: "Partial to full sun",
        toughness: "Medium",
        tips: [],
        promotion: false,
        rating: 4.9,
        bestseller: false,
        indoor: true,
        outdoor: true,
        maintenance: "Daily",
        expierience: "Intermediate",
        space: "Large Space (e.g. large Room)",
        purpose: "Food (e.g. herbs or vegetables",
        petfriendly: true,
        allergyfriendly: true,
        imageUrl: ["/Citrus_limon1.png", "/Citrus_limon2.png", "/Citrus_limon3.png"],
        nickname: "",
        size: NaN,
        age: NaN,
        pinned: false,
        timeBetweenSessions: 1440,
        waterTime: new Date(Date.now() + 60 * 1000)
    },
    {
        id: 10,
        name: "Orchid",
        scientificName: "Orchidaceae",
        price: 18.99,
        description: "To be added",
        inStock: true,
        category: ["flower"],
        water: 30,
        toxicity: false,
        humidity: "high humidity",
        temperature: "20-30",
        sunlight: "Partial sun",
        toughness: "Medium",
        tips: [],
        promotion: false,
        rating: 4.7,
        bestseller: true,
        indoor: true,
        outdoor: true,
        maintenance: "Daily",
        expierience: "Intermediate",
        space: "Medium Space (e.g. Windowsill)",
        purpose: "Decoration",
        petfriendly: true,
        allergyfriendly: true,
        imageUrl: ["/Orchidaceae1.png", "/Orchidaceae2.png", "/Orchidaceae3.png"],
        nickname: "",
        size: NaN,
        age: NaN,
        pinned: false,
        timeBetweenSessions: 1440,
        waterTime: new Date(Date.now() + 60 * 1000)
    },
    {
        id: 11,
        name: "Venus flytrap",
        scientificName: "Dionaea muscipula",
        price: 6.99,
        description: "To be added",
        inStock: true,
        category: ["carnivorous"],
        water: 10,
        toxicity: false,
        humidity: "high humidity",
        temperature: "25-40",
        sunlight: "Partial to full sun",
        toughness: "Medium",
        tips: [],
        promotion: false,
        rating: 4.8,
        bestseller: false,
        indoor: true,
        outdoor: true,
        maintenance: "Daily",
        expierience: "Advanced",
        space: "Small space (e.g. small desk)",
        purpose: "Decoration",
        petfriendly: true,
        allergyfriendly: true,
        imageUrl: ["/Dionaea_muscipula1.png", "/Dionaea_muscipula2.png", "/Dionaea_muscipula3.png"],
        nickname: "",
        size: NaN,
        age: NaN,
        pinned: false,
        timeBetweenSessions: 1440,
        waterTime: new Date(Date.now() + 60 * 1000)
    }
];
